services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=rosadb'
      - 'POSTGRES_PASSWORD=jumentoalado123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'